### ISSUE TITLE
generate fr and de - 2815

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/cloud-manager-data-sense#36]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by dmajones** [comment]
Looks like TMS picked up the changes from Tom. 
Sites (fr-fr& de-de) are up and running.
Total TOT: 7 minutes.
