### ISSUE TITLE
Docker Requirements

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/cloud-manager-data-sense#41]
Page: [Deploy Cloud Data Sense on a Linux host that has internet access](https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html)

Hello all!

Something to take back internally... per the CDS team the CDS installer does not install Docker. That's something that has to be done manually. The doc site says that Docker is installed as part of the CDS installer process, so a bit of a confict there. Figured I'd follow the proper channel and open a ticket so y'all can work with the CDS team to get this straitened out.

Thanks!

**Comment by netapp-tonacki** [comment]
Hi TheFalldog,  I had seen some discussion in Teams about this.  Thanks for letting me know that is the final answer - not shipped anymore...  A new release is going out very soon, so I can make that change now so it will go live with that release.  

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi TheFalldog,  The Data Sense release went out yesterday, so the information about Docker being installed automatically has been removed.

Thanks for letting me know.

Tom
