### ISSUE TITLE
Install instructions can be expanded with an example when Activate option not available on UI.

### ISSUE THREAD

**Issue by anee04** [NetAppDocs/cloud-manager-data-sense#64]
Page: [Install BlueXP classification on a host that has internet access](https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html)

Example:
sudo ./install.sh -a **account-0aocgfH2** -c wu8CSFSDrCAhC7Xgr7sSFGfnPjFfyqmR**clients** -t eyJhbGciOiJSxxxxxxxxxx

For the agent ID - Kindly mention explicitly that it is Connector Client ID (as customer can tend to use system ID)
For the agent ID - we had to add **clients** for it work based on instruction copy from lab as it does not work otherwise and customer UI did not give Activate instructions or option to uninstall. Please highlight the clients in bold in example as it is not part of agent ID when copied.
And for Bearer token - no keyword Bearer required (gets copied on UI copy value from developer window automatically) so above example would help.

**Comment by netapp-tonacki** [comment]
Hi anee04.  Thanks for your comment.  I had used "_client_id_" in another location in the docs, but you are correct that I left it as "_agent_id_" in a couple places.  I am making that change in the syntax examples now.  I will also be changing the description of the parameter from "_agent_id_ = Connector ID" to "_client_id_ = Connector Client ID".

I don't really understand the need to add "clients" to the end of the Client ID parameter. I have forwarded this question to the team to see what they know about having to manually add "clients".   I'll let you know what I find out.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Anee04,  I received an answer that, like you said, the user needs to add "clients" manually if they get the Connector Client ID manually. When Data Sense  (BlueXP classification) provides the required command it includes "clients" in that command. Most, of not all, users will get the command this way, so hopefully this does not come up much.  But I did add this text to the steps: "(_add the suffix "clients" to the client ID if it not already there_)" just in case.

I am waiting for 1 more thing and then I will publish the docs with these changes.

Tom

**Comment by netapp-tonacki** [comment]
Hi anee04,  I have pushed these changes live to the doc site.  Thanks again for your comment.

Tom
