### ISSUE TITLE
license limit reached

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloud-manager-data-sense#7]
Page: [Frequently asked questions about Cloud Data Sense](https://docs.netapp.com/us-en/occm/faq_cloud_compliance.html)

can we please add another question about what will happen when we reach the license limit with cloud data sense in the FAQ?
for ex: if a custy has 50TB BYOL and they reach the limit what happens? i know we pop a warning, but would like to know if they will be switched to Paygo if they scan beyond 50TB....

**Comment by netapp-tonacki** [comment]
Hi Sabari,  I see I missed part of your question. Whether you hit the limit by reaching the expiration date, or by reaching the max amount of data to scan, both are considered "license expired".  I think it stops scanning, but I am double-checking with the team and I will let you know - and update the doc.

Our new doc site went live yesterday, so you'll see updates in the [new page for Cloud Data Sense](https://docs.netapp.com/us-en/cloud-manager-data-sense/index.html) from now on.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Sabari,  I got the official word; and it is different than what I originally thought.  Thanks again for bringing this up.  [I updated the docs here](https://docs.netapp.com/us-en/cloud-manager-data-sense/task-licensing-datasense.html#byol-license-considerations).  Briefly:

- When the BYOL expires by reaching capacity or expiration date, scanning continues, but you can't view information in Dashboards about the scanned data.
- If you have a PAYGO too, when BYOL expires it is not switched over to PAYGO - you must renew the BYOL.

Thanks, Tom
